import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { IoDocumentsOutline } from "react-icons/io5";
import { CiSearch } from "react-icons/ci";
import Link from 'next/link';
import { VscSettingsGear } from "react-icons/vsc";
import Image from 'next/image';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen w-screen overflow-hidden bg-dark text-white  flex flex-col"}>
        <main className=" flex overflow-y-auto h-full flex-grow  ">
          {children}

        </main>

      </body>
    </html>
  )
}
